import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#D3EFFF',
    paddingHorizontal: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo: {
    width: 280,
    height: 200,
    resizeMode: 'contain',
    marginBottom: 10,
  },
  title: {
    color: '#256489',
    fontSize: 24,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 30,
  },
  instructionText: {
    color: '#256489',
    fontSize: 16, 
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    marginBottom: 30,
    paddingHorizontal: 20,
    lineHeight: 24,
  },
  codeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '80%',
    marginBottom: 40,
  },
  codeInput: {
    width: 40,
    height: 50,
    backgroundColor: '#C9EBFF',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'rgba(37, 100, 137, 0.3)',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: 'Montserrat-Bold',
    color: '#256489',
  },
  continueButton: {
    backgroundColor: '#256489',
    borderRadius: 30,
    padding: 15,
    width: '80%',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    marginBottom: 15,
  },
  continueButtonText: {
    color: 'white',
    fontSize: 18,
    fontFamily: 'Montserrat-Bold',
    letterSpacing: 0.5,
  },
  resendCodeButton: {
    marginTop: 10,
  },
  resendCodeText: {
    color: '#256489',
    fontSize: 14,
    fontFamily: 'Montserrat-Bold',
    textDecorationLine: 'underline',
  },
});