import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 80,
  },
  continueShoppingContainer: {
    alignItems: 'center',
    marginBottom: 25,
  },
  continueShoppingButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#256489',
    padding: 16,
    borderRadius: 30,
    width: 305,
    height: 54,
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cartIcon: {
    width: 30,
    height: 30,
    marginRight: 5,
    tintColor: '#fff',
  },
  continueText: {
    fontSize: 14,
    color: '#fff',
    fontFamily: 'Montserrat-Bold',
  },
  itemCard: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#f0f0f0',
    alignItems: 'center',
  },
  productImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    resizeMode: 'contain',
    marginRight: 16,
  },
  productInfoContainer: {
    flex: 1,
  },
  itemName: {
    fontSize: 15,
    fontFamily: 'Montserrat-SemiBold',
    color: '#333',
    marginBottom: 8,
    lineHeight: 20,
  },
  itemPrice: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    color: '#006516',
    marginBottom: 8,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  quantityButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#006516',
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityText: {
    fontSize: 16,
    color: '#fff',
    fontFamily: 'Montserrat-Bold',
    lineHeight: 20,
  },
  quantity: {
    fontSize: 15,
    fontFamily: 'Montserrat-SemiBold',
    minWidth: 24,
    textAlign: 'center',
    color: '#333',
    marginHorizontal: 8,
  },
  trashButton: {
    padding: 8,
    marginLeft: 8,
  },
  trashIcon: {
    width: 32,
    height: 32,
    tintColor: '#666',
  },
  totalCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#f9f9f9',
    padding: 20,
    borderRadius: 12,
    marginVertical: 16,
    borderWidth: 1,
    borderColor: '#eaeaea',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  totalLabel: {
    fontSize: 17,
    fontFamily: 'Montserrat-Bold',
    color: '#333',
  },
  totalValue: {
    fontSize: 17,
    fontFamily: 'Montserrat-Bold',
    color: '#006516',
  },
  section: {
    marginBottom: 20,
    backgroundColor: '#FFF',
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#f0f0f0',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 16,
    color: '#333',
  },
  
  // Delivery Options Styles
  deliveryOptionsContainer: {
    marginTop: 8,
  },
  deliveryOptionCard: {
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  deliveryOptionCardActive: {
    borderColor: '#006516',
    backgroundColor: '#E8F5E9',
  },
  deliveryOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deliveryRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#006516',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deliveryRadioSelected: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#006516',
  },
  deliveryOptionText: {
    fontSize: 15,
    fontFamily: 'Montserrat-SemiBold',
    color: '#333',
  },
  deliveryAddressText: {
    fontSize: 13,
    fontFamily: 'Montserrat-Medium',
    color: '#006516',
    marginTop: 8,
    marginLeft: 32,
  },
  
  // Payment Methods Styles
  paymentMethodsContainer: {
    marginTop: 8,
  },
  paymentMethodCard: {
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  paymentMethodCardActive: {
    borderColor: '#006516',
    backgroundColor: '#E8F5E9',
  },
  paymentMethodContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  paymentMethodImage: {
    marginRight: 12,
    resizeMode: 'contain',
  },
  pixImage: {
    width: 36,
    height: 36,
  },
  cardImage: {
    width: 40,
    height: 28,
  },
  paymentMethodText: {
    fontSize: 15,
    fontFamily: 'Montserrat-SemiBold',
    color: '#333',
  },
  paymentMethodSubtext: {
    fontSize: 13,
    fontFamily: 'Montserrat-Medium',
    color: '#666',
    marginTop: 2,
  },
  
  // Confirm Button
  confirmButtonContainer: {
    alignItems: 'center',
    marginVertical: 16,
  },
  confirmButton: {
    backgroundColor: '#006516',
    padding: 18,
    borderRadius: 30,
    alignItems: 'center',
    width: 310,
    height: 60,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  confirmButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    letterSpacing: 0.5,
  },
});

// Navigation Bar Styles
export const navStyles = StyleSheet.create({
  bottomNavigation: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#fff",
    height: 80,
    paddingBottom: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    elevation: 10,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    width: "25%",
  },
  navIconContainer: {
    position: "relative",
    alignItems: "center",
    marginBottom: 4,
  },
  activeIndicator: {
    position: "absolute",
    top: -8,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#256489",
  },
  navIcon: {
    width: 24,
    height: 24,
  },
  navLabel: {
    fontSize: 12,
    color: "#256489",
    fontFamily: "Montserrat-Medium",
  },
});